### ISSUE TITLE
Proposal for changes on the schedule page

### ISSUE THREAD

**Issue by DanielProductDesigner** [devoteam-se/competence-assistant#338]
1. Change the word “My votes” into  “My personal schedule”.  
2. Remove the “Favorite sessions only”.  
3. Place the “Clear all” button in the bottom on the filter menu. 

Link to the design proposal in Figma: 
https://www.figma.com/file/mkG9tk4fLHacp7lQXiJAfg/KD-Competence-Cards?type=design&node-id=1356%3A3239&mode=design&t=58fzWfj3lHCM7SzO-1

**Comment by a-game** [comment]
Filter has been reworked, closing.
