### ISSUE TITLE
Proposal for aligning design styles

### ISSUE THREAD

**Issue by DanielProductDesigner** [devoteam-se/competence-assistant#339]
Align the pages for administration with the rest of the application. Using a grey line around the content instead of shadow. 

Link to the design proposal in Figma: 
https://www.figma.com/file/mkG9tk4fLHacp7lQXiJAfg/KD-Competence-Cards?type=design&node-id=1352%3A3152&mode=design&t=58fzWfj3lHCM7SzO-1

**Comment by a-game** [comment]
Done!
