### ISSUE TITLE
Make it possible for the users to mark a session as favorite from the schedule when a session is opened in a modal.  

### ISSUE THREAD

**Issue by DanielProductDesigner** [devoteam-se/competence-assistant#343]
Make it possible for the users to mark a session as favorite from the schedule when a session is opened in a modal.  

Add the favorite icon the session modal when it's opened from the schedule. Preferably the favorite icon is placed in the same position as it is on a "session card" for the user to find it easier.

**Comment by a-game** [comment]
Done!
